# Downloading data from DATASUS

In [1]:
# Installing the library we used to download the data from DATASUS
%pip install pandas pysus

Requirement already satisfied: pandas in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: pysus in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (1.0.0)
Requirement already satisfied: numpy>=1.23.2 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pandas) (2025.3)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (1.4.0)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (0.21.4)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (0.12.5)
Requirement already satisfied: dateparser<2.0.0,>=1.1.8 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (1.3.0)
Requirement already satisfied: dbfread==2.0.7 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (2.0.7)
Requirement already satisfied: elasticsearch==7.16.2 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (7.16.2)
Requirement already satisfied: fastparquet<=2024.11.0,>=2023.10.1 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (2024.11.0)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (4.15.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (0.6.0)
Requirement already satisfied: pyarrow>=11.0.0 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (23.0.0)
Requirement already satisfied: pycparser==2.21 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (2.21)
Requirement already satisfied: pyreaddbc>=1.1.0 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (1.2.0)
Requirement already satisfied: tqdm==4.64.0 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (4.64.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (4.15.0)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (2.6.16)
Requirement already satisfied: wget<4.0,>=3.2 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pysus) (3.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (1.26.20)
Requirement already satisfied: certifi in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (2026.1.4)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: regex>=2024.9.11 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2026.1.15)
Requirement already satisfied: tzlocal>=0.2 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (2.11.0)
Requirement already satisfied: fsspec in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (2026.2.0)
Requirement already satisfied: packaging in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (25.0)
Requirement already satisfied: wcwidth in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.6.0)
Requirement already satisfied: cffi<2,>=1.15.1 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pyreaddbc>=1.1.0->pysus) (1.17.1)
Requirement already satisfied: pyyaml>=6 in /home/carolina/Documents/TCC Documentos/TCC/.conda/lib/python3.11/site-packages (from pyreaddbc>=1.1.0->pysus) (6.0.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Databases that will be used
from pysus.online_data import SIM, SIH, CNES

# python libraries
import os

## DOWNLOAD

In [3]:
data_SIM = SIM.download(groups=["cid10"],states='SP', years=2022)
data_SIM

28630082it [00:00, 63976168062.30it/s]

/home/carolina/pysus/DOSP2022.parquet

In [4]:
data_SIH = SIH.download(groups="SP", states="SP",  months=[1], years=2022 )
data_SIH

61784247it [00:00, 49729785900.80it/s]

/home/carolina/pysus/SPSP2201.parquet

In [5]:
data_CNES = CNES.download(group='LT', states='SP', years=2023, months=1)
data_CNES

99462it [00:00, 396553103.09it/s]

/home/carolina/pysus/LTSP2301.parquet

## MAKE DFs

In [6]:
df_SIM = data_SIM.to_dataframe()
print(df_SIM.shape)
df_SIM.head()

(354056, 87)

,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,...,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA,CONTADOR
0,1,2,26122022,,835,355030,05041977,445,2,1,...,,,M,,,,,,,1045502
1,1,2,26122022,1652,835,355030,22021976,446,2,1,...,,,M,,,,,,,1045503
2,1,2,26122022,1557,835,355030,19101980,442,2,4,...,,,M,,,,,,,1045504
3,1,2,15112022,0845,835,355030,23091960,462,2,1,...,,,,,,,,,,1045505
4,1,2,27122022,0948,835,355030,28041985,437,2,3,...,,,M,,,,,,,1045506

In [7]:
df_SIH = data_SIH.to_dataframe()
print(df_SIH.shape)
df_SIH.head()

(3407996, 36)

,SP_GESTOR,SP_UF,SP_AA,SP_MM,SP_CNES,SP_NAIH,SP_PROCREA,SP_DTINTER,SP_DTSAIDA,SP_NUM_PR,...,SP_PF_DOC,SP_PJ_DOC,IN_TP_VAL,SEQUENCIA,REMESSA,SERV_CLA,SP_CIDPRI,SP_CIDSEC,SP_QT_PROC,SP_U_AIH
0,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,980016277727031,00000006053858,1,974,HM35095001N202201.DTS,126006,I269,0000,20,0
1,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,980016277727031,00000006053858,1,974,HM35095001N202201.DTS,126006,I269,0000,18,0
2,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,980016277727031,00000006053858,1,974,HM35095001N202201.DTS,126006,I269,0000,7,0
3,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,708602091447387,00000006053858,1,974,HM35095001N202201.DTS,000000,I269,0000,24,0
4,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,708602091447387,00000006053858,1,974,HM35095001N202201.DTS,000000,I269,0000,27,0

In [8]:
df_CNES = data_CNES.to_dataframe()
print(df_CNES.shape)
df_CNES.head()

(8308, 28)

,CNES,CODUFMUN,REGSAUDE,MICR_REG,DISTRSAN,DISTRADM,TPGESTAO,PF_PJ,CPF_CNPJ,NIV_DEP,...,NIV_HIER,TERCEIRO,TP_LEITO,CODLEITO,QT_EXIST,QT_CONTR,QT_SUS,QT_NSUS,COMPETEN,NAT_JUR
0,2077647,350010,0209,,,,M,3,53221255006777,1,...,,,2,33,63,0,24,39,202301,3999
1,2077647,350010,0209,,,,M,3,53221255006777,1,...,,,5,68,1,0,1,0,202301,3999
2,2077647,350010,0209,,,,M,3,53221255006777,1,...,,,4,10,9,0,6,3,202301,3999
3,2077647,350010,0209,,,,M,3,53221255006777,1,...,,,2,31,2,0,2,0,202301,3999
4,2077647,350010,0209,,,,M,3,53221255006777,1,...,,,4,43,8,0,4,4,202301,3999

## CLEAN

In [9]:
df_SIH

,SP_GESTOR,SP_UF,SP_AA,SP_MM,SP_CNES,SP_NAIH,SP_PROCREA,SP_DTINTER,SP_DTSAIDA,SP_NUM_PR,...,SP_PF_DOC,SP_PJ_DOC,IN_TP_VAL,SEQUENCIA,REMESSA,SERV_CLA,SP_CIDPRI,SP_CIDSEC,SP_QT_PROC,SP_U_AIH
0,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,980016277727031,00000006053858,1,974,HM35095001N202201.DTS,126006,I269,0000,20,0
1,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,980016277727031,00000006053858,1,974,HM35095001N202201.DTS,126006,I269,0000,18,0
2,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,980016277727031,00000006053858,1,974,HM35095001N202201.DTS,126006,I269,0000,7,0
3,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,708602091447387,00000006053858,1,974,HM35095001N202201.DTS,000000,I269,0000,24,0
4,350950,35,2022,01,6053858,3522105835260,0303060140,20211113,20220118,,...,708602091447387,00000006053858,1,974,HM35095001N202201.DTS,000000,I269,0000,27,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3407991,353740,35,2022,01,2083027,3522106929902,0408050918,20220119,20220120,,...,000000000000000,00000002083027,1,32,HM35374001N202201.DTS,000000,M201,0000,1,0
3407992,353740,35,2022,01,2083027,3522106929913,0408050462,20220119,20220122,,...,170556761670007,00000000000000,2,33,HM35374001N202201.DTS,000000,M938,0000,0,1
3407993,353740,35,2022,01,2083027,3522106929913,0408050462,20220119,20220122,,...,103282640990003,00000000000000,2,33,HM35374001N202201.DTS,000000,M938,0000,0,0
3407994,353740,35,2022,01,2083027,3522106929913,0408050462,20220119,20220122,,...,000000000000000,00000002035456,1,33,HM35374001N202201.DTS,000000,M938,0000,1,0
3407995,353740,35,2022,01,2083027,3522106929913,0408050462,20220119,20220122,,...,000000000000000,00000002035456,1,33,HM35374001N202201.DTS,000000,M938,0000,1,0